### ISSUE TITLE
Simple Upscale example workflow produces jumbled images

### ISSUE THREAD

**Issue by Jellybit** [shiimizu/ComfyUI-TiledDiffusion#15]
I loaded the example Simple Upscale workflow from the readme, but get some strange results, no matter what checkpoint I use.

Here's the base image it makes, which looks good enough to me, though different than your example despite using the same checkpoint:
![ComfyUI_00002a_](https://github.com/shiimizu/ComfyUI-TiledDiffusion/assets/6216400/16c4c25e-0fb1-47d9-b5a6-58ac53801b64)

However, after upscale, it becomes this:
![ComfyUI_00002b_](https://github.com/shiimizu/ComfyUI-TiledDiffusion/assets/6216400/3fb4d153-91a8-45f3-b47d-52c48c5bc996)

I'm using the same ControlNet model, and checkpoint. I touched nothing else. The 4x Upscale example seems to work fine.

![ComfyUI_00002_](https://github.com/shiimizu/ComfyUI-TiledDiffusion/assets/6216400/5096d0ef-8d21-492d-af20-08b4c93faefe)

**Comment by shiimizu** [comment]
Related to #9
