### ISSUE TITLE
Excuse me, I cannot find an option similar to the magnification factor in the existing node

### ISSUE THREAD

**Issue by Executesong** [shiimizu/ComfyUI-TiledDiffusion#16]
Excuse me, I cannot find an option similar to the magnification factor in the existing node. How can I enlarge the resolution of the image? Thank you so much!

**Comment by Executesong** [comment]
![Uploading 微信图片_20240217183330.png…]()

**Comment by shiimizu** [comment]
See https://comfyanonymous.github.io/ComfyUI_examples/2_pass_txt2img/

**Comment by Executesong** [comment]
Thank you very much!!
