### ISSUE TITLE
 Error: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by Vigilence** [shiimizu/ComfyUI-TiledDiffusion#37]
I have been doing some tests with the flux model.  I noticed there is an issue if I have the clip and vae assigned to the cpu.  Is there a chance we can get the tiled decode and encode nodes to support the force set nodes for the clip and vae models?

If I use the internal comfyui tiled encode and decode I can avoid this error, but if I use the encode and decode tile nodes from your nodes then I receive the error above.

![Screenshot 2024-09-05 084026](https://github.com/user-attachments/assets/3685dd0b-3fe2-4d75-b44f-4caccace4a12)
![Screenshot 2024-09-05 084020](https://github.com/user-attachments/assets/b38f8fe8-26fe-4bcb-986a-efcdb299db7e)
![Screenshot 2024-09-05 084219](https://github.com/user-attachments/assets/c11e058e-65b5-4146-84fc-cdff7e8160d1)
![Screenshot 2024-09-05 084215](https://github.com/user-attachments/assets/305077e9-3d1b-4dde-9d1f-76ae75ecfc9a)

```
# ComfyUI Error Report
## Error Details
- **Node Type:** VAEEncodeTiled_TiledDiffusion
- **Exception Type:** RuntimeError
- **Exception Message:** Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
## Stack Trace
```

![Screenshot 2024-09-05 084559](https://github.com/user-attachments/assets/b3a5d192-5896-47ca-a3b5-014980cbddb3)

**Comment by shiimizu** [comment]
I tried the nodes, but it works for me? Do you have the full error log? It's long and should look something like `https://github.com/shiimizu/ComfyUI-TiledDiffusion/issues/21`

**Comment by Vigilence** [comment]
Yes, I will share it as a txt file since it’s so long.

**Comment by Vigilence** [comment]
The issue still persists with the latest update.  The build in tiled vae decode and vae encode nodes work fine.
