### ISSUE TITLE
Missing attributes issue

### ISSUE THREAD

**Issue by victorca25** [shiimizu/ComfyUI-TiledDiffusion#53]
Not a major issue, but these lines:
https://github.com/shiimizu/ComfyUI-TiledDiffusion/blob/28398098dfcf8c5252a968650c599527bb9fa961/tiled_diffusion.py#L357

https://github.com/shiimizu/ComfyUI-TiledDiffusion/blob/28398098dfcf8c5252a968650c599527bb9fa961/tiled_diffusion.py#L360

Should be updated to match the condition like in these lines:
https://github.com/shiimizu/ComfyUI-TiledDiffusion/blob/28398098dfcf8c5252a968650c599527bb9fa961/tiled_diffusion.py#L381

https://github.com/shiimizu/ComfyUI-TiledDiffusion/blob/28398098dfcf8c5252a968650c599527bb9fa961/tiled_diffusion.py#L385

To avoid runtime errors when the controlnet doesn't have the "vae" or "latent_format" attributes

**Comment by shiimizu** [comment]
Thanks for the heads up!
