### ISSUE TITLE
Controlnet image applies to each tile insted of the hole image.

### ISSUE THREAD

**Issue by 49RpK5dY** [shiimizu/ComfyUI-TiledDiffusion#6]
After ca0ed33ac0aa648983f2fe7e8423bf4dc6b0cc6e Apply ControlNet (Advanced) applies to each tile individually creating a grid of cloned images.
[example](https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/ecb9afdf-de6c-40a3-9baa-94fd1723d2b6/original=true/20240113_121224%203142.jpeg)

**Comment by shiimizu** [comment]
I can't seem to reproduce that issue. Do you have a workflow I can test?

**Comment by 49RpK5dY** [comment]
After some additional testing it turned out this happens when `tile_batch_size` is set to 1 witch is pretty much the only way I can run this in most cases.

[test.json](https://github.com/shiimizu/ComfyUI-TiledDiffusion/files/13929818/test.json)

**Comment by shiimizu** [comment]
Thanks for the workflow. It should be fixed in https://github.com/shiimizu/ComfyUI-TiledDiffusion/commit/820fe869988c3986973323bb371f46367881c947.

**Comment by 49RpK5dY** [comment]
Can confirm that it works as intended now. Thanks.
